name: dwds_livestream
services:
  db:
    image: postgres:16-alpine
    environment:
      - "POSTGRES_USER=lexdb"
      - "POSTGRES_PASSWORD=lexdb"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    image: docker.zdl.org/zdl/dwds-livestream:latest
    build:
      context: .
    network_mode: host
    environment:
      - "DWDS_LIVESTREAM_ACCESS_LOG=/log/access.log"
      - "DWDS_LIVESTREAM_WBDB_USER=${DWDS_LIVESTREAM_WBDB_USER:-dwdswb}"
      - "DWDS_LIVESTREAM_WBDB_PASSWORD=${DWDS_LIVESTREAM_WBDB_PASSWORD:-dwdswb}"
    volumes:
      - ./data:/log
volumes:
  db:
